import {Platform} from 'react-native';
import {RouteProp} from '@react-navigation/native';
import {NativeStackNavigationProp} from '@react-navigation/native-stack';
export interface ScreenProps {
  navigation: NativeStackNavigationProp<any>;
  route: RouteProp<any, any>;
}

export const MAX_PRICE = 5000000;
export const MAX_SEATS = 72;
export const AppHorizontalMargin = 19;
export const AppImages = {
  Common: {
    backBtn: require('../assets/newImages/Common/backBtn.png'),
    dropDown: require('../assets/newImages/Common/dropDown.png'),
    crossImg: require('../assets/newImages/Common/crossImg.png'),
    searchIcon: require('../assets/newImages/Common/searchIcon.png'),
    favUnselected: require('../assets/newImages/Common/favUnselected.png'),
    tick: require('../assets/newImages/Common/tick.png'),
    check: require('../assets/newImages/Common/check.png'),
    uncheck: require('../assets/newImages/Common/uncheck.png'),
    radioUnselected: require('../assets/newImages/Common/radioUnselected.png'),
    radioSelected: require('../assets/newImages/Common/radioSelected.png'),
    favSelected: require('../assets/newImages/Common/favSelected.png'),
    profileImagePlaceHolder: require('../assets/newImages/Common/profileImagePlaceHolder.png'),
    male: require('../assets/newImages/Common/male.png'),
    female: require('../assets/newImages/Common/female.png'),
    other: require('../assets/newImages/Common/other.png'),
    msgIcon: require('../assets/newImages/Common/msgIcon.png'),
    nextMsgIcon: require('../assets/newImages/Common/nextMsgIcon.png'),
    dummyPdf: require('../assets/newImages/Common/dummyPdf.png'),
    up: require('../assets/newImages/Common/up.png'),
    voiceMic: require('../assets/newImages/Common/voiceMic.png'),
    deleteVoice: require('../assets/newImages/Common/deleteVoice.png'),
    pause: require('../assets/newImages/Common/pause.png'),
    send: require('../assets/newImages/Common/send.png'),
    voiceLargeIcon: require('../assets/newImages/Common/voiceLargeIcon.png'),
    starIcon: require('../assets/newImages/Common/starIcon.png'),
    deleteIcon: require('../assets/newImages/Common/deleteIcon.png'),
  },
  Journey: {
    journeyBackground: require('../assets/newImages/Journey/journeyBackground.png'),
    journeyCar: require('../assets/newImages/Journey/journeyCar.png'),
    journeyStar: require('../assets/newImages/Journey/journeyStar.png'),
    steering: require('../assets/newImages/Journey/steering.png'),
    dollarBudget: require('../assets/newImages/Journey/dollarBudget.png'),
    calendar: require('../assets/newImages/Journey/calendar.png'),
  },
  Home: {
    background: require('../assets/newImages/Main/backgroundImage.png'),
    homeLogo: require('../assets/newImages/Main/homeLogo.png'),
    dropDown: require('../assets/newImages/Main/dropDown.png'),
    filterIcon: require('../assets/newImages/Main/filterIcon.png'),
    homeAnimatedIcon: require('../assets/newImages/Main/homeAnimatedIcon.png'),
    descMapBanner: require('../assets/newImages/Main/descMapBanner.png'),
    matchingBg: require('../assets/newImages/Main/matchingBg.png'),
    auctionBg: require('../assets/newImages/Main/auctionBg.png'),
    partyAuctionBg: require('../assets/newImages/Main/partyAuctionBg.png'),
    certifiedBanner: require('../assets/newImages/Main/certifiedBanner.png'),
    smallCertifiedBanner: require('../assets/newImages/Main/smallCertifiedBanner.png'),
  },
  MainSearch: {
    sortingIcon: require('../assets/newImages/MainSearch/sortingIcon.png'),
    largeList: require('../assets/newImages/MainSearch/largeList.png'),
    listView: require('../assets/newImages/MainSearch/listView.png'),
    smallCalendar: require('../assets/newImages/MainSearch/smallCalendar.png'),
    smallMilege: require('../assets/newImages/MainSearch/smallMilege.png'),
    smallEngine: require('../assets/newImages/MainSearch/smallEngine.png'),
    smallTransmission: require('../assets/newImages/MainSearch/smallTransmission.png'),
    colorCar: require('../assets/newImages/MainSearch/colorCar.png'),
    radio: require('../assets/newImages/MainSearch/radio.png'),
    radioSelected: require('../assets/newImages/MainSearch/radioSelected.png'),
  },
  dummy: {
    hondaIcon: require('../assets/newImages/Dummy/dummyHonda.png'),
    dummyCarThumbnail: require('../assets/newImages/Dummy/dummyCarThumbnail.png'),
    dummyBodyType: require('../assets/newImages/Dummy/dummyBodyType.png'),
    dummyAnim: require('../assets/newImages/Dummy/dummyAnim.png'),
    dummyLargeCar: require('../assets/newImages/Dummy/dummyLargeCar.png'),
    dummyReviewImg: require('../assets/newImages/Dummy/dummyReviewImg.png'),
    dummyFlag: require('../assets/newImages/Dummy/dummyFlag.png'),
    dummyRoboImg: require('../assets/newImages/Dummy/dummyRoboImg.png'),
  },
  BottomBar: {
    homeIcon: require('../assets/newImages/BottomBar/homeIcon.png'),
    favIcon: require('../assets/newImages/BottomBar/favIcon.png'),
    menuIcon: require('../assets/newImages/BottomBar/menuIcon.png'),
    homeSelectedIcon: require('../assets/newImages/BottomBar/homeSelectedIcon.png'),
    favSelectedIcon: require('../assets/newImages/BottomBar/favSelectedIcon.png'),
    menuSelectedIcon: require('../assets/newImages/BottomBar/menuSelectedIcon.png'),
    ArIcon: require('../assets/newImages/BottomBar/ArIcon.png'),
    ArIconSelected: require('../assets/newImages/BottomBar/ArIconSelected.png'),
    agenticIcon: require('../assets/newImages/BottomBar/agenticIcon.png'),
    agenticIconSelected: require('../assets/newImages/BottomBar/agenticIconSelected.png'),
  },
  Splash: {
    splashIcon: require('../assets/newImages/Splash/splashIcon.png'),
  },
  RefineSearch: {},
  Detail: {
    shareIcon: require('../assets/newImages/Detail/shareIcon.png'),
    background: require('../assets/newImages/Detail/detailBackground.png'),
    whatsappImg: require('../assets/newImages/Detail/whatsappImg.png'),
    upward: require('../assets/newImages/Detail/upward.png'),
    downward: require('../assets/newImages/Detail/downward.png'),
  },
  Auth: {
    hidePass: require('../assets/newImages/Auth/hidePass.png'),
    showPass: require('../assets/newImages/Auth/showPass.png'),
    emailIcon: require('../assets/newImages/Auth/emailIcon.png'),
    gmailIcon: require('../assets/newImages/Auth/gmailIcon.png'),
    facebookIcon: require('../assets/newImages/Auth/facebookIcon.png'),
    appleIcon: require('../assets/newImages/Auth/appleIcon.png'),
  },
  Account: {
    accountAboutUs: require('../assets/newImages/Account/accountAboutUs.png'),
    accountContactUs: require('../assets/newImages/Account/accountContactUs.png'),
    accountCurrency: require('../assets/newImages/Account/accountCurrency.png'),
    accountFaqs: require('../assets/newImages/Account/accountFaqs.png'),
    accountHowItWork: require('../assets/newImages/Account/accountHowItWork.png'),
    accountLedger: require('../assets/newImages/Account/accountLedger.png'),
    accountPrivacyPolicy: require('../assets/newImages/Account/accountPrivacyPolicy.png'),
    accountSmartAuction: require('../assets/newImages/Account/accountSmartAuction.png'),
    accountSmartMatching: require('../assets/newImages/Account/accountSmartMatching.png'),
    accountSuccessStories: require('../assets/newImages/Account/accountSuccessStories.png'),
    accountTerms: require('../assets/newImages/Account/accountTerms.png'),
    accountThirdPartyAuction: require('../assets/newImages/Account/accountThirdPartyAuction.png'),
    accountInquiry: require('../assets/newImages/Account/accountInquiry.png'),
    accountOrder: require('../assets/newImages/Account/accountOrder.png'),
    accountHistory: require('../assets/newImages/Account/accountHistory.png'),
    editBtn: require('../assets/newImages/Account/editBtn.png'),
    contactWhatsapp: require('../assets/newImages/Account/contactWhatsapp.png'),
    contactPhone: require('../assets/newImages/Account/contactPhone.png'),
    contactEmail: require('../assets/newImages/Account/contactEmail.png'),
    minus: require('../assets/newImages/Account/minus.png'),
    plus: require('../assets/newImages/Account/plus.png'),
    deleteMain: require('../assets/newImages/Account/deleteMain.png'),
  },
  Order: {
    active: require('../assets/newImages/Order/active.png'),
    completed: require('../assets/newImages/Order/completed.png'),
    pending: require('../assets/newImages/Order/pending.png'),
    consigneeConfirmIcon: require('../assets/newImages/Order/consigneeConfirmIcon.png'),
    pdfPlaceHolder: require('../assets/newImages/Order/pdfPlaceHolder.png'),
    confirmReceived: require('../assets/newImages/Order/confirmReceived.png'),
    congratsImg: require('../assets/newImages/Order/congratsImg.png'),
  },
  Smart: {
    centerImg: require('../assets/newImages/Smart/centerImg.png'),
    smartStar: require('../assets/newImages/Smart/smartStar.png'),
    crossSmart: require('../assets/newImages/Smart/crossSmart.png'),
    micSmart: require('../assets/newImages/Smart/micSmart.png'),
    tickSmart: require('../assets/newImages/Smart/tickSmart.png'),
  },
};

export const AppFonts = {
  PoppinBold: 'Poppins-Bold',
  PoppinsExtraLight: 'Poppins-ExtraLight',
  PoppinMedium: 'Poppins-Medium',
  PoppinsLight: 'Poppins-Light',
  PoppinsRegular: 'Poppins-Regular',
  PoppinsSemiBold: 'Poppins-SemiBold',
};
export const dateFormater = {
  fullDate2: 'YYYY-MM-DD hh:mm a',
  fullDate: 'YYYY-MM-DD HH:mm:ss.SSS Z',
  date: 'DD/MM/YYYY',
  time: 'hh:mm a',
  timeDay: 'dddd, DD MMM',
  days: 'dddd, DD',
  monthYear: 'MMMM YYYY',
  short: 'd MMM yyyy',
};
